FROM rocker/geospatial:4.1.2

RUN R -e "install.packages('plyr')"
RUN R -e "install.packages('dplyr')"
RUN R -e "install.packages('ggplot2')"
RUN R -e "install.packages('lubridate')"
RUN R -e "install.packages('ggforce')"
RUN R -e "install.packages('cowplot')"
RUN R -e "devtools::install_github('tidyverse/lubridate')"
RUN R -e "install.packages('tsiR')"
RUN R -e "install.packages('kernlab')"
RUN R -e "install.packages('reshape2')"
RUN R -e "install.packages('pracma')"
RUN R -e "install.packages('astsa')"
RUN R -e "install.packages('GADMTools')"
RUN R -e "install.packages('plotrix')"
RUN R -e "install.packages('plm')"
RUN R -e "install.packages('interp')"
RUN R -e "install.packages('gplots')"
RUN R -e "install.packages('lfe')"
RUN R -e "install.packages('ggpubr')"
RUN R -e "install.packages('stargazer')"
RUN R -e "install.packages('ggnewscale')"
